### ISSUE TITLE
competitionBot

### ISSUE THREAD

**Issue by christopherni** [NRG948/NRGRobot2016#134]
Create a public static boolean competitionBot in Robot.

Use the ternary operator to set the following values in AcquirerArm:
VOLTS_0 = 3.425 if competitionBot true, 3.585 if false
VOLTS_90 = 2.160 if true, 2.170 if false

ShooterArm:
VOLTS_0 = 1.075 if true, 1.050 if false

**Comment by gregoryquick** [comment]
Completed by Jasonlee05077  at https://github.com/NRG948/NRGRobot2016/commit/7b09348b8ef44eaa4e00a0b3356c5cb4f3c69779, and remember to reference the issue the commit is in response to...
