### ISSUE TITLE
AcquireTo command

### ISSUE THREAD

**Issue by christopherni** [NRG948/NRGRobot2016#14]
Create an RaiseAcquirerTo command in the Acquirer subsystem that raises the acquirer to the given level. No need for PID.

**Comment by gregoryquick** [comment]
Possible code for this submitted at https://github.com/NRG948/NRGRobot2016/pull/21

**Comment by gregoryquick** [comment]
Compled by another person at https://github.com/NRG948/NRGRobot2016/commit/8d3c6ba976d084e8ed1306ae29e1732dc2750fba
