### ISSUE TITLE
Change RaiseAcquirerTo

### ISSUE THREAD

**Issue by christopherni** [NRG948/NRGRobot2016#68]
Rename the enum in Robot to Level.
Add a constructor to RaiseAcquirerTo to take in a Level instead of an angle and modify the rest of the command accordingly.

**Comment by gregoryquick** [comment]
Just so you know all issues that I believe I have completed I assign to you so you see it. If this is not what I should be doing just let me know, I will continue to do this unless you tell me to stop.
