### ISSUE TITLE
ManualClimb command

### ISSUE THREAD

**Issue by christopherni** [NRG948/NRGRobot2016#86]
Create a ManualClimb command. isFinished() should return false. Create four member variables: EXTEND_WINCH_POWER, EXTEND_TAPEMEASURE_POWER, WIND_WINCH_POWER, AND WIND_TAPEMEASURE_POWER. The constructor should take in a boolean extend. If extend is true, set the winch and tapemeasure motors to the appropriate powers. If it is false, set them to the other powers.

**Comment by majesticfish** [comment]
Set this command as the default command
